### ISSUE TITLE
ubuntu-24.04: cannot start the database (EphemeralMongo7 1.1.3)

### ISSUE THREAD

**Issue by marco-merola-ef** [asimmon/ephemeral-mongo#57]
Hi, I am getting this error when trying to start the MongoRunner on a github job runner with `ubuntu-24.04`

`Error Message:
   System.TimeoutException : MongoDB connection availability took longer than the specified timeout of 30 seconds. Consider increasing the value of 'ConnectionTimeout'.
  Stack Trace:
     at EphemeralMongo.MongodProcess.StartAndWaitForConnectionReadiness()
   at EphemeralMongo.MongodProcess.Start()
   at EphemeralMongo.MongoRunner.RunInternal()
   at EphemeralMongo.MongoRunner.Run(MongoRunnerOptions options)`

Any suggestions?

**Comment by mdhom** [comment]
Do you get this error on every run, or only on the second run? If so, can you manuall kill the currently running mongod process and try again? That helps me, see #58.

**Comment by wouterSeyen** [comment]
I'm experiencing the same issue. We have a dotnet solution with several xUnit test projects performing tests using EphemeralMongo.

I use following command to run my tests: `dotnet test MySolution.sln`

Locally (on Macbook Pro with M2 chip), this works without any issues. 

However, in a docker build using mcr.microsoft.com/dotnet/sdk:8.0 as base image, this results in the same error as described in bug description.

**Comment by marco-merola-ef** [comment]
@wouterSeyen I managed to solve it by using dotnet test container for mongo: https://dotnet.testcontainers.org/modules/mongodb/

**Comment by timneil** [comment]
I'm experiencing the same issue. Did anyone solve it using Ephemeral Mongo? Is it running in mcr.microsoft.com/dotnet/sdk for anyone?

**Comment by asimmon** [comment]
I believe this is fixed in [2.0.0](https://github.com/asimmon/ephemeral-mongo/releases/tag/2.0.0):

- The default Linux MongoDB edition is now the one for Ubuntu 22.04 (not 18.04).
- The CI is currently running with .NET 9 projects on Ubuntu 24.04. I tried 22.04, too. They both work.
